# ===== Build =====
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ./TaskManager/*.csproj ./TaskManager/
RUN dotnet restore ./TaskManager/*.csproj
COPY ./TaskManager ./TaskManager
RUN dotnet publish ./TaskManager/*.csproj -c Release -o /out

# ===== Run =====
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /out ./
# .NET 8 en contenedores usa 8080 por defecto
# Y Koyeb ya expone un PORT usare ese nomas
ENV ASPNETCORE_HTTP_PORTS=${PORT}
EXPOSE 8080
CMD ["dotnet", "TaskManager.dll"]  # <-- cambia por el nombre real
